### PR TITLE
Read from master flag should be a global variable

### LINKED ISSUE #5: AR Slave forces a DB connection on precompile
Hi,
After I added AR Slave gem to my project and database.yml it fails due to this gem now requiring DB connection during ``RAILS_ENV=production bundle exec rake assets:precompile``.

It wasn't required before.

Any ideas?

### PR DESCRIPTION
**Pull request by reidmorrison**
### Issue # (if available)

Fixes #5, #10, and #20

### Description of changes

- read_from_master! is supposed to be a global and not thread specific variable.
- Use ActiveRecord::Base.configurations so that Active Record Replica can be disabled when the relevant database has not yet been created.
- Don't install when primary database is not available.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: lib/active_record_replica/version.rb [hunk 1]
```diff
@@ -1,3 +1,3 @@
 module ActiveRecordReplica
-  VERSION = '2.0.2'
+  VERSION = '2.1.0'
```
Comment (goodgravy) [inline lib/active_record_replica/version.rb:2]: Perhaps this should be v3 because this a non-backwards compatible change?
```suggestion
  VERSION = '3.0.0'
```

**Review by goodgravy — CHANGES_REQUESTED** [review]
👏  thanks so much for this Reid—code looks great, I just have the comment about a version.

Before merging and pushing I would do some smoke tests in our apps and whatnot—did you have anything like that you used to do in your workflow or would you lean 100% on the test suite?

**Comment by goodgravy** [comment]
@reidmorrison following up here: I'm happy to move forward with this PR if we just bump the version

**Review by goodgravy — APPROVED** [review]
